2015/10/22 16:05:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "-áº¥c".' in C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php(141): CWebApplication->runController('-\xE1\xBA\xA5c')
#1 C:\xampp\htdocs\xechieuve\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\xechieuve\protected\components\WebApplicationEndBehavior.php(24): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('user')
#4 C:\xampp\htdocs\xechieuve\framework\base\CComponent.php(261): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\xechieuve\index.php(11): CComponent->__call('runEnd', Array)
#6 C:\xampp\htdocs\xechieuve\index.php(11): CWebApplication->runEnd('user')
#7 {main}
REQUEST_URI=/xechieuve/index.php-%E1%BA%A5c
---
2015/10/22 16:06:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "aavbdbe".' in C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php(141): CWebApplication->runController('aavbdbe')
#1 C:\xampp\htdocs\xechieuve\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\xechieuve\protected\components\WebApplicationEndBehavior.php(24): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('user')
#4 C:\xampp\htdocs\xechieuve\framework\base\CComponent.php(261): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\xechieuve\index.php(11): CComponent->__call('runEnd', Array)
#6 C:\xampp\htdocs\xechieuve\index.php(11): CWebApplication->runEnd('user')
#7 {main}
REQUEST_URI=/xechieuve/aavbdbe
---
2015/10/22 16:06:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "avfa".' in C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php(141): CWebApplication->runController('avfa')
#1 C:\xampp\htdocs\xechieuve\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\xechieuve\protected\components\WebApplicationEndBehavior.php(24): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('user')
#4 C:\xampp\htdocs\xechieuve\framework\base\CComponent.php(261): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\xechieuve\index.php(11): CComponent->__call('runEnd', Array)
#6 C:\xampp\htdocs\xechieuve\index.php(11): CWebApplication->runEnd('user')
#7 {main}
REQUEST_URI=/xechieuve/avfa
---
2015/10/22 16:09:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "avfa".' in C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php(141): CWebApplication->runController('avfa')
#1 C:\xampp\htdocs\xechieuve\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\xechieuve\protected\components\WebApplicationEndBehavior.php(24): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('user')
#4 C:\xampp\htdocs\xechieuve\framework\base\CComponent.php(261): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\xechieuve\index.php(11): CComponent->__call('runEnd', Array)
#6 C:\xampp\htdocs\xechieuve\index.php(11): CWebApplication->runEnd('user')
#7 {main}
REQUEST_URI=/xechieuve/avfa
---
2015/10/22 16:09:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "avfa".' in C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php(141): CWebApplication->runController('avfa')
#1 C:\xampp\htdocs\xechieuve\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\xechieuve\protected\components\WebApplicationEndBehavior.php(24): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('user')
#4 C:\xampp\htdocs\xechieuve\framework\base\CComponent.php(261): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\xechieuve\index.php(11): CComponent->__call('runEnd', Array)
#6 C:\xampp\htdocs\xechieuve\index.php(11): CWebApplication->runEnd('user')
#7 {main}
REQUEST_URI=/xechieuve/avfa
---
2015/10/22 16:10:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "avfa".' in C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php(141): CWebApplication->runController('avfa')
#1 C:\xampp\htdocs\xechieuve\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\xechieuve\protected\components\WebApplicationEndBehavior.php(24): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('user')
#4 C:\xampp\htdocs\xechieuve\framework\base\CComponent.php(261): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\xechieuve\index.php(11): CComponent->__call('runEnd', Array)
#6 C:\xampp\htdocs\xechieuve\index.php(11): CWebApplication->runEnd('user')
#7 {main}
REQUEST_URI=/xechieuve/avfa
---
2015/10/22 16:10:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "avfa".' in C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php(141): CWebApplication->runController('avfa')
#1 C:\xampp\htdocs\xechieuve\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\xechieuve\protected\components\WebApplicationEndBehavior.php(24): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('user')
#4 C:\xampp\htdocs\xechieuve\framework\base\CComponent.php(261): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\xechieuve\index.php(11): CComponent->__call('runEnd', Array)
#6 C:\xampp\htdocs\xechieuve\index.php(11): CWebApplication->runEnd('user')
#7 {main}
REQUEST_URI=/xechieuve/avfa
---
<<<<<<< HEAD
2015/10/21 11:30:51 [error] [php] Undefined variable: currentPage (C:\xampp\htdocs\xechieuve\protected\controllers\user\Khach_tim_xeController.php:171)
Stack trace:
#0 C:\xampp\htdocs\xechieuve\framework\web\CController.php(286): Khach_tim_xeController->runAction()
#1 C:\xampp\htdocs\xechieuve\framework\web\CController.php(265): Khach_tim_xeController->runActionWithFilters()
#2 C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php(282): Khach_tim_xeController->run()
#3 C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\xechieuve\framework\base\CApplication.php(184): CWebApplication->processRequest()
#5 C:\xampp\htdocs\xechieuve\protected\components\WebApplicationEndBehavior.php(24): CWebApplication->run()
#6 unknown(0): WebApplicationEndBehavior->runEnd()
#7 C:\xampp\htdocs\xechieuve\framework\base\CComponent.php(261): call_user_func_array()
#8 C:\xampp\htdocs\xechieuve\index.php(11): CWebApplication->__call()
#9 C:\xampp\htdocs\xechieuve\index.php(11): CWebApplication->runEnd()
REQUEST_URI=/xechieuve/khach-tim-xe/dang-tin
in C:\xampp\htdocs\xechieuve\protected\controllers\user\Khach_tim_xeController.php (171)
in C:\xampp\htdocs\xechieuve\protected\components\WebApplicationEndBehavior.php (24)
in C:\xampp\htdocs\xechieuve\index.php (11)
2015/10/22 15:50:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "dsds".' in C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php(141): CWebApplication->runController('dsds')
#1 C:\xampp\htdocs\xechieuve\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\xechieuve\protected\components\WebApplicationEndBehavior.php(24): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('user')
#4 C:\xampp\htdocs\xechieuve\framework\base\CComponent.php(261): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\xechieuve\index.php(11): CComponent->__call('runEnd', Array)
#6 C:\xampp\htdocs\xechieuve\index.php(11): CWebApplication->runEnd('user')
#7 {main}
REQUEST_URI=/xechieuve/dsds
---
=======
>>>>>>> e7a62caf2ab146b9b871b49a10691b9b828f8753
2015/10/22 16:20:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "khach-tim-xe/dang-tindsd".' in C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php(141): CWebApplication->runController('khach-tim-xe/da...')
#1 C:\xampp\htdocs\xechieuve\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\xechieuve\protected\components\WebApplicationEndBehavior.php(24): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('user')
#4 C:\xampp\htdocs\xechieuve\framework\base\CComponent.php(261): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\xechieuve\index.php(11): CComponent->__call('runEnd', Array)
#6 C:\xampp\htdocs\xechieuve\index.php(11): CWebApplication->runEnd('user')
#7 {main}
REQUEST_URI=/xechieuve/khach-tim-xe/dang-tindsd
---
2015/10/22 16:20:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "khach-tim-xe/images/404.png".' in C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php(141): CWebApplication->runController('khach-tim-xe/im...')
#1 C:\xampp\htdocs\xechieuve\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\xechieuve\protected\components\WebApplicationEndBehavior.php(24): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('user')
#4 C:\xampp\htdocs\xechieuve\framework\base\CComponent.php(261): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\xechieuve\index.php(11): CComponent->__call('runEnd', Array)
#6 C:\xampp\htdocs\xechieuve\index.php(11): CWebApplication->runEnd('user')
#7 {main}
REQUEST_URI=/xechieuve/khach-tim-xe/images/404.png
HTTP_REFERER=http://localhost:8888/xechieuve/khach-tim-xe/dang-tindsd
---
2015/10/22 16:21:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "khach-tim-xe/dang-tindsd".' in C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php(141): CWebApplication->runController('khach-tim-xe/da...')
#1 C:\xampp\htdocs\xechieuve\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\xechieuve\protected\components\WebApplicationEndBehavior.php(24): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('user')
#4 C:\xampp\htdocs\xechieuve\framework\base\CComponent.php(261): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\xechieuve\index.php(11): CComponent->__call('runEnd', Array)
#6 C:\xampp\htdocs\xechieuve\index.php(11): CWebApplication->runEnd('user')
#7 {main}
REQUEST_URI=/xechieuve/khach-tim-xe/dang-tindsd
---
2015/10/22 16:21:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "khach-tim-xe/dang-tindsd".' in C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php(141): CWebApplication->runController('khach-tim-xe/da...')
#1 C:\xampp\htdocs\xechieuve\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\xechieuve\protected\components\WebApplicationEndBehavior.php(24): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('user')
#4 C:\xampp\htdocs\xechieuve\framework\base\CComponent.php(261): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\xechieuve\index.php(11): CComponent->__call('runEnd', Array)
#6 C:\xampp\htdocs\xechieuve\index.php(11): CWebApplication->runEnd('user')
#7 {main}
REQUEST_URI=/xechieuve/khach-tim-xe/dang-tindsd
---
2015/10/22 16:21:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "khach-tim-xe/images/404.png".' in C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php(141): CWebApplication->runController('khach-tim-xe/im...')
#1 C:\xampp\htdocs\xechieuve\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\xechieuve\protected\components\WebApplicationEndBehavior.php(24): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('user')
#4 C:\xampp\htdocs\xechieuve\framework\base\CComponent.php(261): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\xechieuve\index.php(11): CComponent->__call('runEnd', Array)
#6 C:\xampp\htdocs\xechieuve\index.php(11): CWebApplication->runEnd('user')
#7 {main}
REQUEST_URI=/xechieuve/khach-tim-xe/images/404.png
HTTP_REFERER=http://localhost:8888/xechieuve/khach-tim-xe/dang-tindsd
---
2015/10/22 16:22:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "rao-vatds".' in C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php(141): CWebApplication->runController('rao-vatds')
#1 C:\xampp\htdocs\xechieuve\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\xechieuve\protected\components\WebApplicationEndBehavior.php(24): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('user')
#4 C:\xampp\htdocs\xechieuve\framework\base\CComponent.php(261): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\xechieuve\index.php(11): CComponent->__call('runEnd', Array)
#6 C:\xampp\htdocs\xechieuve\index.php(11): CWebApplication->runEnd('user')
#7 {main}
REQUEST_URI=/xechieuve/rao-vatds
---
2015/10/22 16:22:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "dsds".' in C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php(141): CWebApplication->runController('dsds')
#1 C:\xampp\htdocs\xechieuve\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\xechieuve\protected\components\WebApplicationEndBehavior.php(24): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('user')
#4 C:\xampp\htdocs\xechieuve\framework\base\CComponent.php(261): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\xechieuve\index.php(11): CComponent->__call('runEnd', Array)
#6 C:\xampp\htdocs\xechieuve\index.php(11): CWebApplication->runEnd('user')
#7 {main}
REQUEST_URI=/xechieuve/dsds
---
2015/10/22 16:24:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "khach-tim-xe/loc-theo-xe/xe-dap/3d".' in C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php(141): CWebApplication->runController('khach-tim-xe/lo...')
#1 C:\xampp\htdocs\xechieuve\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\xechieuve\protected\components\WebApplicationEndBehavior.php(24): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('user')
#4 C:\xampp\htdocs\xechieuve\framework\base\CComponent.php(261): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\xechieuve\index.php(11): CComponent->__call('runEnd', Array)
#6 C:\xampp\htdocs\xechieuve\index.php(11): CWebApplication->runEnd('user')
#7 {main}
REQUEST_URI=/xechieuve/khach-tim-xe/loc-theo-xe/xe-dap/3d
---
2015/10/22 16:24:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "khach-tim-xe/loc-theo-xe/xe-dap/images/404.png".' in C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php(141): CWebApplication->runController('khach-tim-xe/lo...')
#1 C:\xampp\htdocs\xechieuve\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\xechieuve\protected\components\WebApplicationEndBehavior.php(24): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('user')
#4 C:\xampp\htdocs\xechieuve\framework\base\CComponent.php(261): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\xechieuve\index.php(11): CComponent->__call('runEnd', Array)
#6 C:\xampp\htdocs\xechieuve\index.php(11): CWebApplication->runEnd('user')
#7 {main}
REQUEST_URI=/xechieuve/khach-tim-xe/loc-theo-xe/xe-dap/images/404.png
HTTP_REFERER=http://localhost:8888/xechieuve/khach-tim-xe/loc-theo-xe/xe-dap/3d
---
2015/10/22 16:25:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "khach-tim-xe/loc-theo-xe/xe-dap/3d".' in C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php(141): CWebApplication->runController('khach-tim-xe/lo...')
#1 C:\xampp\htdocs\xechieuve\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\xechieuve\protected\components\WebApplicationEndBehavior.php(24): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('user')
#4 C:\xampp\htdocs\xechieuve\framework\base\CComponent.php(261): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\xechieuve\index.php(11): CComponent->__call('runEnd', Array)
#6 C:\xampp\htdocs\xechieuve\index.php(11): CWebApplication->runEnd('user')
#7 {main}
REQUEST_URI=/xechieuve/khach-tim-xe/loc-theo-xe/xe-dap/3d
---
2015/10/22 16:25:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "khach-tim-xe/loc-theo-xe/xe-dap/images/404.png".' in C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php(141): CWebApplication->runController('khach-tim-xe/lo...')
#1 C:\xampp\htdocs\xechieuve\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\xechieuve\protected\components\WebApplicationEndBehavior.php(24): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('user')
#4 C:\xampp\htdocs\xechieuve\framework\base\CComponent.php(261): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\xechieuve\index.php(11): CComponent->__call('runEnd', Array)
#6 C:\xampp\htdocs\xechieuve\index.php(11): CWebApplication->runEnd('user')
#7 {main}
REQUEST_URI=/xechieuve/khach-tim-xe/loc-theo-xe/xe-dap/images/404.png
HTTP_REFERER=http://localhost:8888/xechieuve/khach-tim-xe/loc-theo-xe/xe-dap/3d
---
2015/10/22 16:25:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "khach-tim-xe/loc-theo-xe/xe-dap/3d".' in C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php(141): CWebApplication->runController('khach-tim-xe/lo...')
#1 C:\xampp\htdocs\xechieuve\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\xechieuve\protected\components\WebApplicationEndBehavior.php(24): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('user')
#4 C:\xampp\htdocs\xechieuve\framework\base\CComponent.php(261): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\xechieuve\index.php(11): CComponent->__call('runEnd', Array)
#6 C:\xampp\htdocs\xechieuve\index.php(11): CWebApplication->runEnd('user')
#7 {main}
REQUEST_URI=/xechieuve/khach-tim-xe/loc-theo-xe/xe-dap/3d
---
2015/10/22 16:26:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "khach-tim-xe/loc-theo-xe/xe-dap/3d".' in C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php(141): CWebApplication->runController('khach-tim-xe/lo...')
#1 C:\xampp\htdocs\xechieuve\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\xechieuve\protected\components\WebApplicationEndBehavior.php(24): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('user')
#4 C:\xampp\htdocs\xechieuve\framework\base\CComponent.php(261): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\xechieuve\index.php(11): CComponent->__call('runEnd', Array)
#6 C:\xampp\htdocs\xechieuve\index.php(11): CWebApplication->runEnd('user')
#7 {main}
REQUEST_URI=/xechieuve/khach-tim-xe/loc-theo-xe/xe-dap/3d
---
2015/10/22 16:27:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "khach-tim-xe/loc-theo-xe/xe-dap/3d".' in C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php(141): CWebApplication->runController('khach-tim-xe/lo...')
#1 C:\xampp\htdocs\xechieuve\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\xechieuve\protected\components\WebApplicationEndBehavior.php(24): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('user')
#4 C:\xampp\htdocs\xechieuve\framework\base\CComponent.php(261): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\xechieuve\index.php(11): CComponent->__call('runEnd', Array)
#6 C:\xampp\htdocs\xechieuve\index.php(11): CWebApplication->runEnd('user')
#7 {main}
REQUEST_URI=/xechieuve/khach-tim-xe/loc-theo-xe/xe-dap/3d
---
2015/10/22 16:28:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "lien-he/dÃ¡".' in C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php(141): CWebApplication->runController('lien-he/d\xC3\xA1')
#1 C:\xampp\htdocs\xechieuve\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\xechieuve\protected\components\WebApplicationEndBehavior.php(24): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('user')
#4 C:\xampp\htdocs\xechieuve\framework\base\CComponent.php(261): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\xechieuve\index.php(11): CComponent->__call('runEnd', Array)
#6 C:\xampp\htdocs\xechieuve\index.php(11): CWebApplication->runEnd('user')
#7 {main}
REQUEST_URI=/xechieuve/lien-he/d%C3%A1
---
2015/10/22 16:37:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "khach-tim-xe/xem-chi-tiet/hellohellohellohello/55dsa".' in C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php(141): CWebApplication->runController('khach-tim-xe/xe...')
#1 C:\xampp\htdocs\xechieuve\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\xechieuve\protected\components\WebApplicationEndBehavior.php(24): CApplication->run()
#3 [internal function]: WebApplicationEndBehavior->runEnd('user')
#4 C:\xampp\htdocs\xechieuve\framework\base\CComponent.php(261): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\xechieuve\index.php(11): CComponent->__call('runEnd', Array)
#6 C:\xampp\htdocs\xechieuve\index.php(11): CWebApplication->runEnd('user')
#7 {main}
REQUEST_URI=/xechieuve/khach-tim-xe/xem-chi-tiet/hellohellohellohello/55dsa
---
2015/10/22 16:57:58 [error] [php] Undefined index: Tinkhachhang (C:\xampp\htdocs\xechieuve\protected\controllers\user\Khach_tim_xeController.php:154)
Stack trace:
#0 C:\xampp\htdocs\xechieuve\framework\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#1 C:\xampp\htdocs\xechieuve\framework\web\CController.php(308): CInlineAction->runWithParams()
#2 C:\xampp\htdocs\xechieuve\framework\web\CController.php(286): Khach_tim_xeController->runAction()
#3 C:\xampp\htdocs\xechieuve\framework\web\CController.php(265): Khach_tim_xeController->runActionWithFilters()
#4 C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php(282): Khach_tim_xeController->run()
#5 C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php(141): CWebApplication->runController()
#6 C:\xampp\htdocs\xechieuve\framework\base\CApplication.php(184): CWebApplication->processRequest()
#7 C:\xampp\htdocs\xechieuve\protected\components\WebApplicationEndBehavior.php(24): CWebApplication->run()
#8 unknown(0): WebApplicationEndBehavior->runEnd()
#9 C:\xampp\htdocs\xechieuve\framework\base\CComponent.php(261): call_user_func_array()
#10 C:\xampp\htdocs\xechieuve\index.php(11): CWebApplication->__call()
#11 C:\xampp\htdocs\xechieuve\index.php(11): CWebApplication->runEnd()
REQUEST_URI=/xechieuve/khach-tim-xe/dang-tin
in C:\xampp\htdocs\xechieuve\protected\controllers\user\Khach_tim_xeController.php (154)
in C:\xampp\htdocs\xechieuve\protected\components\WebApplicationEndBehavior.php (24)
in C:\xampp\htdocs\xechieuve\index.php (11)
2015/10/22 16:58:22 [error] [php] Undefined index: Tinkhachhang (C:\xampp\htdocs\xechieuve\protected\controllers\user\Khach_tim_xeController.php:154)
Stack trace:
#0 C:\xampp\htdocs\xechieuve\framework\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#1 C:\xampp\htdocs\xechieuve\framework\web\CController.php(308): CInlineAction->runWithParams()
#2 C:\xampp\htdocs\xechieuve\framework\web\CController.php(286): Khach_tim_xeController->runAction()
#3 C:\xampp\htdocs\xechieuve\framework\web\CController.php(265): Khach_tim_xeController->runActionWithFilters()
#4 C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php(282): Khach_tim_xeController->run()
#5 C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php(141): CWebApplication->runController()
#6 C:\xampp\htdocs\xechieuve\framework\base\CApplication.php(184): CWebApplication->processRequest()
#7 C:\xampp\htdocs\xechieuve\protected\components\WebApplicationEndBehavior.php(24): CWebApplication->run()
#8 unknown(0): WebApplicationEndBehavior->runEnd()
#9 C:\xampp\htdocs\xechieuve\framework\base\CComponent.php(261): call_user_func_array()
#10 C:\xampp\htdocs\xechieuve\index.php(11): CWebApplication->__call()
#11 C:\xampp\htdocs\xechieuve\index.php(11): CWebApplication->runEnd()
REQUEST_URI=/xechieuve/khach-tim-xe/dang-tin
in C:\xampp\htdocs\xechieuve\protected\controllers\user\Khach_tim_xeController.php (154)
in C:\xampp\htdocs\xechieuve\protected\components\WebApplicationEndBehavior.php (24)
in C:\xampp\htdocs\xechieuve\index.php (11)
2015/10/22 17:02:58 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`xechieuve`.`tinkhachhang`, CONSTRAINT `PK_tinkhachhang_khachhang` FOREIGN KEY (`ma_khach_hang`) REFERENCES `khachhang` (`ma_khach_hang`)). The SQL statement executed was: INSERT INTO `tinkhachhang` (`trang_thai`, `nguoi_lien_lac`, `so_dien_thoai`, `tieu_de_tin`, `tinh_thanh`, `noi_dung_tin`, `ma_loai_tin`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6).
in C:\xampp\htdocs\xechieuve\protected\controllers\user\Khach_tim_xeController.php (161)
in C:\xampp\htdocs\xechieuve\protected\components\WebApplicationEndBehavior.php (24)
in C:\xampp\htdocs\xechieuve\index.php (11)
2015/10/22 17:02:58 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`xechieuve`.`tinkhachhang`, CONSTRAINT `PK_tinkhachhang_khachhang` FOREIGN KEY (`ma_khach_hang`) REFERENCES `khachhang` (`ma_khach_hang`)). The SQL statement executed was: INSERT INTO `tinkhachhang` (`trang_thai`, `nguoi_lien_lac`, `so_dien_thoai`, `tieu_de_tin`, `tinh_thanh`, `noi_dung_tin`, `ma_loai_tin`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6)' in C:\xampp\htdocs\xechieuve\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\xechieuve\framework\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 C:\xampp\htdocs\xechieuve\framework\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\xechieuve\protected\controllers\user\Khach_tim_xeController.php(161): CActiveRecord->save(false)
#3 [internal function]: Khach_tim_xeController->actionDang_tin(1)
#4 C:\xampp\htdocs\xechieuve\framework\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(Khach_tim_xeController), Array)
#5 C:\xampp\htdocs\xechieuve\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(Khach_tim_xeController), Object(ReflectionMethod), Array)
#6 C:\xampp\htdocs\xechieuve\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#7 C:\xampp\htdocs\xechieuve\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#8 C:\xampp\htdocs\xechieuve\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php(282): CController->run('dang_tin')
#10 C:\xampp\htdocs\xechieuve\framework\web\CWebApplication.php(141): CWebApplication->runController('khach_tim_xe/da...')
#11 C:\xampp\htdocs\xechieuve\framework\base\CApplication.php(184): CWebApplication->processRequest()
#12 C:\xampp\htdocs\xechieuve\protected\components\WebApplicationEndBehavior.php(24): CApplication->run()
#13 [internal function]: WebApplicationEndBehavior->runEnd('user')
#14 C:\xampp\htdocs\xechieuve\framework\base\CComponent.php(261): call_user_func_array(Array, Array)
#15 C:\xampp\htdocs\xechieuve\index.php(11): CComponent->__call('runEnd', Array)
#16 C:\xampp\htdocs\xechieuve\index.php(11): CWebApplication->runEnd('user')
#17 {main}
REQUEST_URI=/xechieuve/khach-tim-xe/dang-tin
HTTP_REFERER=http://localhost:8888/xechieuve/khach-tim-xe/dang-tin
---
